### ISSUE TITLE
Add support to MySQL on the zdb interface

### ISSUE THREAD

**Issue by emmanuelm41** [Zondax/golem#77]
Nowadays, zdb package only supports clickhouse and postgres. It would be great to add support to MySQL too, as we may need it on the future.

:link: [zboto Link](https://app.clickup.com/t/8693yhbw7)

**Comment by jleni** [comment]
I would consider MySQL very low priority for now. Can we close?

**Comment by emmanuelm41** [comment]
We can... I would leave this here as a reminder, but it is not really urgent
